# -*- coding: utf-8 -*-
"""oxunov1525

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwbEP3oCK-s7kR6jWqjZkgxOceUVRGCZ
"""

import pandas as pn

# 1. DataFrame yaratish
data = {
    'Ism' : ['Ali', 'Vali', 'Sardor','Bekzod', 'Jamshid', 'Ortiqmirzo', 'Abdurahmon', 'Rahimberdi', 'Biloliddin','Samandar'],
    'Yoshi': [25, 30, 22, 25, 23, 19, 21, 27, 18, 22],
    'Shahar' : ['Toshkent', 'Xorazm', 'Andijon', 'Navoiy', 'Namangan', 'Andijon', 'Fargona', 'Andijon', 'Fargona', 'Fargona']

}
df = pn.DataFrame(data)

#2. Ma'lumotlarni ko'rish
print(df)

#3. Filtrlash
young_people = df[df['Yoshi']< 30]
print("30 yoshdan kichiklar:\n",young_people)

#4. O'zgartirish
df['Yoshi'] += 1 # Har bir shaxsning yoshini 1 ga oshirish
print("Yangilangan DataFrame :\n",df)
#5. Manzil
manzil = df[df['Shahar']=='Fargona']
print("Manzili Fargonaliklar :\n",manzil)